import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import test from 'node:test';

test('production renderer exposes only the structured V2 operations surface', async () => {
  const [html, renderer, catalog, styles, preload, main, ipc, manifest] = await Promise.all([
    fs.readFile('renderer/v2/index.html', 'utf8'),
    fs.readFile('renderer/v2/app.js', 'utf8'),
    fs.readFile('renderer/v2/plugin-catalog.js', 'utf8'),
    fs.readFile('renderer/v2/styles.css', 'utf8'),
    fs.readFile('src/preload.cjs', 'utf8'),
    fs.readFile('src/main.mjs', 'utf8'),
    fs.readFile('src/ipc-v2.mjs', 'utf8'),
    fs.readFile('package.json', 'utf8'),
  ]);

  assert.match(html, /id="moreEnvironments"/);
  assert.match(html, /id="confirmationButton"/);
  assert.match(html, /id="confirmationView"/);
  assert.doesNotMatch(html, /id="confirmationDialog"/);
  assert.match(html, /id="deletePluginDialog"/);
  assert.match(html, /id="queryDatabases"/);
  assert.match(html, /id="toggleProjectRail"/);
  assert.match(html, /id="projectRailResizeHandle"/);
  assert.match(html, /id="projectOverviewStats"/);
  assert.match(html, /id="projectOverviewAttention"/);
  assert.match(html, /id="projectOverviewActivity"/);
  assert.match(html, /id="showInlineEnvironmentCreate"/);
  assert.match(html, /id="resourceEnvironmentCreateForm"/);
  assert.doesNotMatch(html, /id="environmentManagerDialog"/);
  assert.doesNotMatch(html, /id="overviewAddEnvironment"|class="action-menu"/);
  assert.match(html, /id="scopeInfoView"/);
  assert.match(html, /id="scopeInfoContent"/);
  assert.doesNotMatch(html, /id="projectTitleEditor"|id="projectSettingsShortcut"|id="projectDeleteShortcut"/);
  assert.match(html, /id="pluginConfigView"/);
  assert.match(html, /id="pluginTypePicker"/);
  assert.match(html, /id="pluginTypeChoices"/);
  assert.match(html, /id="pluginFormDepot"/);
  assert.match(html, /<select id="pluginType"[^>]*><\/select>/);
  assert.match(html, /<input id="pluginDisplayName"(?=[^>]*maxlength="120")(?![^>]*\brequired\b)[^>]*>/);
  assert.match(html, /id="pluginDisplayNameHint"/);
  assert.match(html, /id="pluginTypeIdentity"[^>]*class="plugin-type-identity"/);
  assert.match(html, /id="pluginAdvancedSummary"/);
  assert.match(html, /id="pluginFormSafetyNote"|class="plugin-form-safety-note"/);
  assert.match(html, /id="pluginValidationSection"/);
  assert.match(html, /id="validateServerDraft"/);
  assert.match(html, /id="validateMysqlDatabase"/);
  assert.match(html, /id="validateRedisDraft"/);
  assert.match(html, /id="validateTlsDraft"/);
  assert.match(html, /<input id="pluginDatabase"[^>]*list="pluginDatabaseOptions"/);
  assert.match(html, /<datalist id="pluginDatabaseOptions"/);
  assert.doesNotMatch(html, /<select id="pluginDatabase"/);
  assert.match(html, /id="pluginAdvancedSettings"/);
  assert.match(html, /id="primaryCredentialStatus"/);
  assert.match(html, /id="pluginFormDiagnostic"/);
  assert.match(html, /id="credentialMigrationNotice"/);
  assert.match(html, /id="savePluginDraft"/);
  assert.match(html, /id="savePluginDraftOverflow"/);
  assert.match(html, /id="deleteCurrentDraft"/);
  assert.match(html, /id="auditBody" class="audit-list"/);
  assert.match(html, /id="clearAudit"/);
  assert.match(html, /id="clearAuditDialog"/);
  assert.match(html, /value="pending">等待确认/);
  assert.match(html, /href="#i-app"/);
  assert.match(html, /id="i-panel-left-open"/);
  assert.match(html, /id="i-panel-left-close"/);
  assert.match(html, /id="i-panel-right-open"/);
  assert.match(html, /id="i-panel-right-close"/);
  assert.doesNotMatch(html, /id="i-panel"/);
  assert.doesNotMatch(html, /id="overviewManageEnvironments"/);
  assert.match(html, /id="projectSettingsDialog"/);
  assert.match(html, /id="deleteProjectDialog"/);
  assert.match(html, /data-password-target="pluginPassword"/);
  assert.doesNotMatch(`${html}\n${renderer}`,/\*{5}/);
  assert.doesNotMatch(html, /id="pluginDialog"|id="diagnosticDialog"|<th>发起者<\/th>/);
  assert.doesNotMatch(html, /id="pluginSearch"|id="pluginTypeFilter"|id="pluginStatusFilter"|plugin-filters/);
  const dialogs = [...html.matchAll(/<dialog\b([^>]*)>([\s\S]*?)<\/dialog>/g)];
  assert.ok(dialogs.length >= 6, 'expected the remaining destructive and selection dialogs in the V2 surface');
  for (const [, attributes, contents] of dialogs) {
    const dialogId = attributes.match(/\bid="([^"]+)"/)?.[1];
    const labelledBy = attributes.match(/\baria-labelledby="([^"]+)"/)?.[1];
    assert.ok(dialogId, 'each dialog must keep a stable id');
    assert.ok(labelledBy, `${dialogId} must expose an accessible name`);
    assert.ok(contents.includes(`<h2 id="${labelledBy}"`), `${dialogId} must reference its visible title`);
  }
  assert.match(html, /id="toast"[^>]*aria-atomic="true"[^>]*aria-relevant="additions text"/);
  assert.doesNotMatch(renderer, /pluginFilter|clear-plugin-filter/);
  assert.doesNotMatch(renderer, /manager-current|当前查看/);
  assert.match(renderer, /prepare-delete-plugin/);
  assert.doesNotMatch(renderer, /api\.listPluginDatabases/);
  assert.match(renderer, /api\.probePluginDraft/);
  assert.match(renderer, /api\.cancelPluginProbe/);
  assert.match(renderer, /function checkAndCreateNewPlugin/);
  assert.match(renderer, /pluginFormInstanceId/);
  assert.match(renderer, /newPluginInstanceId/);
  assert.match(renderer, /'检查并添加'/);
  assert.match(renderer, /revealCredential/);
  assert.match(renderer, /navigationGeneration/);
  assert.match(renderer, /projectRailExpanded/);
  assert.match(renderer, /PROJECT_RAIL_WIDTH_KEY/);
  assert.match(renderer, /#i-panel-left-close/);
  assert.match(renderer, /setPointerCapture/);
  assert.match(renderer, /resourcePreview/);
  assert.match(renderer, /data-overview-rename-environment/);
  assert.match(renderer, /data-overview-delete-environment/);
  assert.doesNotMatch(renderer, /data-overview-manage-environment/);
  assert.match(renderer, /data-overview-add-resource/);
  assert.match(renderer, /handleOverviewPluginRuntimeAction/);
  assert.match(renderer, /api\.requestConnectionIntent/);
  assert.doesNotMatch(renderer, /api\.(?:connectEnvironment|retryEnvironment|disconnectEnvironment|cancelEnvironment|connectPlugin|disconnectPlugin)/);
  assert.match(renderer, /function runtimeFacts/);
  assert.match(renderer, /USER_DISCONNECTED/);
  assert.match(renderer, /连接未连接项/);
  assert.match(renderer, /connected > 0 \|\| runtime\.phase === 'reconnecting'/);
  assert.match(renderer, /environment-overview-issue empty/);
  assert.doesNotMatch(renderer, /environment-type-chips/);
  assert.match(renderer, /loadProjectOverviewActivity/);
  assert.match(renderer, /filter\(overviewActivityVisible\)\.slice\(0,5\)/);
  assert.match(renderer, /本机保存的凭据会继续保留/);
  assert.match(renderer, /本机加密凭据不会随项目删除/);
  assert.match(renderer, /function confirmCredentialMigration/);
  assert.match(renderer, /不需要重新输入密码/);
  assert.doesNotMatch(renderer, /rail-project-manage|data-project-settings/);
  assert.match(renderer, /startAddPlugin/);
  assert.match(renderer, /pluginInlineFormHost/);
  assert.doesNotMatch(renderer, /data-action="test-plugin"/);
  assert.match(renderer, /function confirmRuntimeHostKeyChallenge/);
  assert.match(renderer, /api\.confirmConnectionChallenge/);
  assert.doesNotMatch(renderer, /function confirmAndSaveObservedHostKey/);
  assert.match(renderer, /确认信任并保存此指纹吗/);
  assert.match(renderer, /function diagnosticStepDefinitions/);
  assert.match(renderer, /totalElapsedMs/);
  assert.match(renderer, /api\.preparePluginConnectionEdit/);
  assert.match(renderer, /修改名称/);
  assert.doesNotMatch(renderer, /pluginMetadataDescription/);
  assert.doesNotMatch(renderer, /pluginMetadataTags/);
  assert.doesNotMatch(renderer, /pluginMetadataOrder/);
  assert.match(renderer, /api\.beginPluginConnectionEdit/);
  assert.match(renderer, /api\.validatePluginDraft/);
  assert.match(renderer, /validatePluginDraftAction\(['"]tls['"]\)/);
  assert.match(renderer, /api\.cancelPluginValidation/);
  assert.match(renderer, /api\.savePluginConnectionEdit/);
  assert.match(renderer, /api\.cancelPluginConnectionEdit/);
  assert.match(renderer, /api\.savePluginDraft/);
  assert.match(renderer, /api\.resumePluginDraft/);
  assert.match(renderer, /api\.cancelPluginDraftSession/);
  assert.match(renderer, /api\.deletePluginDraft/);
  assert.match(renderer, /api\.promotePluginDraft/);
  assert.match(renderer, /resourcePaneDrafts/);
  assert.doesNotMatch(renderer, /api\.testPlugin/);
  assert.doesNotMatch(renderer, /renderDiagnosticPanel|pluginDiagnostics|connectionCheckPanel/);
  assert.doesNotMatch(preload, /testPlugin|onPluginTestProgress|v2:plugin-test/);
  assert.doesNotMatch(ipc, /v2:plugin-test|plugin-test-progress/);
  assert.match(preload, /probePluginDraft:[^\n]*v2:plugin-probe/);
  assert.match(preload, /cancelPluginProbe:[^\n]*v2:plugin-probe-cancel/);
  assert.match(ipc, /handleWithEvent\('plugin-probe'/);
  assert.match(ipc, /handleWithEvent\('plugin-probe-cancel'/);
  assert.match(renderer, /api\.updatePluginMetadata/);
  assert.match(renderer, /api\.updatePluginAgentConfiguration/);
  assert.match(renderer, /\$\('#pluginType'\)\.setAttribute\('tabindex','-1'\)/);
  assert.match(renderer, /function pluginRuntimeWarningMessage/);
  assert.match(renderer, /clearTransientRevealedCredentials\(\{discardEdited:true\}\)/);
  assert.match(renderer, /pluginRuntimeWarningMessage\(result,'delete',scope\.displayName\)/);
  assert.doesNotMatch(renderer, /diagnostic-facts|结果依据/);
  assert.doesNotMatch(renderer, /diagnosticDialog.*showModal/);
  assert.match(renderer, /saveProjectTitleEdit/);
  assert.match(renderer, /function renderProjectInformation/);
  assert.match(renderer, /function renderEnvironmentInformation/);
  assert.match(renderer, /state\.selectionKind === 'project'/);
  assert.match(renderer, /\['information','概览'\]/);
  assert.doesNotMatch(renderer, /data-environment-overview-details/);
  assert.match(renderer, /environment-overview-content/);
  assert.doesNotMatch(renderer, /resource-environment-head[^`]*data-resource-rename-environment/s);
  assert.doesNotMatch(renderer, /resource-environment-head[^`]*data-resource-delete-environment/s);
  assert.match(renderer, /saveInlineEnvironmentCreate/);
  assert.match(renderer, /data-resource-environment-editor/);
  assert.match(renderer, /data-resource-environment-delete-prompt/);
  assert.doesNotMatch(renderer, /openEnvironmentManager|renderEnvironmentManager/);
  assert.doesNotMatch(renderer, /resource-environment-menu|环境更多操作/);
  assert.doesNotMatch(renderer, /resource-chevron|resourceToggleEnvironment/);
  assert.match(renderer, /permission-summary-item/);
  assert.match(renderer, /permissions-page/);
  assert.match(renderer, /api\.deleteProject/);
  assert.match(renderer, /slice\(0,2\)/);
  assert.match(renderer, /配置和密码已保存，但连接失败/);
  assert.match(renderer, /function pluginDiagnosticConfigurationIssue/);
  assert.match(html, /验证所选数据库/);
  assert.match(renderer, /Agent 已添加插件/);
  assert.match(renderer, /任意绝对路径；敏感内容也原样返回/);
  assert.match(renderer, /所有服务器变更逐次确认/);
  assert.match(renderer, /data-approval-level/);
  assert.match(renderer, /function renderConfirmationCenter/);
  assert.match(renderer, /confirmation-execution/);
  assert.match(renderer, /api\.clearAudit/);
  assert.match(renderer, /pending:'等待确认'/);
  assert.match(renderer, /我已核对上面的完整命令/);
  assert.doesNotMatch(renderer, /这是任意 Shell 命令，可能修改或删除数据、停止服务。确认已经逐字核对/);
  assert.doesNotMatch(renderer, /data-policy-key|save-policy|discard-policy/);
  assert.doesNotMatch(preload, /savePolicy|v2:plugin-policy/);
  assert.match(styles, /\.rail-confirmation-button/);
  assert.match(styles, /\.confirmation-page-shell/);
  assert.match(styles, /\.scope-confirmation-badge/);
  assert.match(styles, /\.policy-state\.strong/);
  assert.match(styles, /\.delete-blockers/);
  assert.match(styles, /\.project-rail-resize-handle/);
  assert.match(styles, /\.project-overview-stats/);
  assert.match(styles, /\.environment-resource-row/);
  assert.match(styles, /\.environment-resource-action/);
  assert.match(styles, /\.overview-attention-row:only-child/);
  assert.match(styles, /\.environment-overview-issue\.empty/);
  assert.match(styles, /\.plugin-inline-form-host/);
  assert.match(styles, /\.audit-record/);
  assert.doesNotMatch(styles, /\.connection-check-section|\.connection-section-head(?!ing)|\.connection-diagnostic/);
  assert.match(styles, /\.diagnostic-steps/);
  assert.match(styles, /\.connection-facts/);
  assert.doesNotMatch(styles, /\.connection-fact-card|\.connection-route-card/);
  assert.doesNotMatch(styles, /\.plugin-danger-zone/);
  assert.match(styles, /\.plugin-form-diagnostic/);
  assert.match(styles, /\.credential-migration-notice/);
  assert.match(styles, /\.resource-environment-create/);
  assert.match(styles, /\.resource-environment-rename-form/);
  assert.match(styles, /\.scope-delete-decision/);
  assert.match(styles, /\.scope-information-page/);
  assert.match(styles, /\.scope-information-actions/);
  assert.match(styles, /\.scope-overview-stats/);
  assert.doesNotMatch(styles, /\.environment-overview-details/);
  assert.match(styles, /\.environment-overview-content/);
  assert.match(styles, /\.environment-overview-attention/);
  assert.doesNotMatch(styles, /\.environment-danger-zone/);
  assert.match(styles, /@container scope-detail \(max-width:719px\)/);
  assert.match(styles, /\.resource-draft-row/);
  assert.match(styles, /\.permission-hero/);
  assert.match(styles, /\.permissions-page \.policy-row/);
  assert.match(styles, /@container \(max-width:650px\)/);
  assert.match(styles, /button:disabled:is\(\[data-busy="true"\],\[aria-busy="true"\]\)/);
  assert.match(styles, /\.plugin-inline-form-host \.dialog-actions\{[^}]*bottom:0/s);
  assert.doesNotMatch(styles, /bottom:-\d/);
  assert.match(styles, /\[data-environment-runtime-action="disconnect"\]\.danger-subtle/);
  assert.match(styles, /\[data-overview-plugin-action="disconnect"\]\.resource-plugin-action/);
  assert.match(styles, /--faint:#82848e/);
  assert.match(styles, /\.rail-expanded \.project-tree-item\.active>\.project-tree-head/);
  assert.match(styles, /\.rail-expanded \.project-tree-item:not\(\.active\)\[data-project-state="connected"\]>\.project-tree-head\{[^}]*box-shadow:inset 3px 0 #55d6a1/s);
  assert.match(styles, /\.rail-expanded \.project-tree-item\[data-project-state="connected"\] \.rail-project-copy small\{[^}]*color:#72dcb0/s);
  assert.match(styles, /\.rail-expanded \.project-tree-item\.active\[data-project-state="connected"\]>\.project-tree-head\{[^}]*box-shadow:inset 3px 0 #55d6a1,[^}]*rgba\(131,124,246,/s);
  assert.ok(
    styles.lastIndexOf('@container (max-width:360px)')
      > styles.lastIndexOf('.resource-environment-head:has(>.scope-confirmation-badge){grid-template-columns'),
    'the extra-narrow resource header contract must override the late single-row rule',
  );

  assert.match(preload, /contextBridge\.exposeInMainWorld\('aiOps', \{\s*v2:/s);
  assert.match(preload, /v2:plugin-delete/);
  assert.match(preload, /v2:plugin-credential-migration-confirm/);
  assert.match(preload, /v2:project-delete/);
  assert.match(preload, /v2:plugin-connection-edit-prepare/);
  assert.match(preload, /v2:plugin-connection-edit-begin/);
  assert.match(preload, /v2:plugin-draft-validate/);
  assert.match(preload, /v2:plugin-validation-cancel/);
  assert.match(preload, /v2:plugin-connection-edit-save/);
  assert.match(preload, /v2:plugin-connection-edit-cancel/);
  assert.match(preload, /v2:plugin-draft-save/);
  assert.match(preload, /v2:plugin-draft-resume/);
  assert.match(preload, /v2:plugin-draft-edit-cancel/);
  assert.match(preload, /v2:plugin-draft-delete/);
  assert.match(preload, /v2:plugin-draft-promote/);
  assert.match(catalog, /defaultPort/);
  assert.match(catalog, /capabilities:\{resourceDiscovery:/);
  assert.match(catalog, /validationPurpose:/);
  assert.match(catalog, /pluginCatalogByType/);
  assert.match(preload, /requestConnectionIntent/);
  assert.match(preload, /v2:connection-intent/);
  assert.match(preload, /v2:confirmation-list/);
  assert.match(preload, /v2:audit-clear/);
  assert.doesNotMatch(preload, /project:delete/);
  assert.doesNotMatch(preload, /project:execute/);
  assert.doesNotMatch(preload, /project:upload/);
  assert.doesNotMatch(preload, /project:download/);
  assert.doesNotMatch(main, /registerIpc\(/);
  assert.doesNotMatch(main, /new SshBroker/);
  assert.match(ipc, /handle\('connection-intent'/);

  const packageJson = JSON.parse(manifest);
  assert.match(packageJson.scripts.check,/renderer\/v2\/plugin-catalog\.js/);
  assert.ok(packageJson.build.files.includes('renderer/v2/**/*'));
  assert.ok(!packageJson.build.files.includes('renderer/**/*'));
  assert.ok(packageJson.build.files.includes('!src/mcp.mjs'));
});
