const assert=require('node:assert/strict');

module.exports=async function({win,fixture,click,fill,waitFor,testId,screenshot,selectPlugin,PRIMARY_ID,plugins,state,runtime}){
  const evaluate=async source=>{try{return await win.webContents.executeJavaScript(source,true);}catch(error){throw new Error("界面脚本执行失败："+source.slice(0,220),{cause:error});}};
  const visible='[data-testid=mysql-data-editor]';
  const cell=(index,name)=>visible+' tbody tr:nth-child('+index+') [data-edit-column="'+name+'"]';
  const current=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+')?.textContent');
  const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await new Promise(resolve=>setTimeout(resolve,90));};
  const enter=async()=>{await waitFor(win,'document.querySelector("[data-testid=mysql-data-editor] tbody tr")','显示结果表格');assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-edit-open]"))'),false);};
  const doubleClick=async selector=>{
    await waitFor(win,'!document.querySelector("[role=dialog]")','等待弹窗退出动画结束');
    const point=await evaluate('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');e.scrollIntoView({block:"nearest",inline:"nearest"});const r=e.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()');
    const hit=await evaluate('document.elementFromPoint('+point.x+','+point.y+')?.outerHTML');
    assert.ok(await evaluate('document.querySelector('+JSON.stringify(selector)+')?.contains(document.elementFromPoint('+point.x+','+point.y+'))'), '双击坐标必须落在目标单元格：'+hit);
    for(const count of [1,2]){win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:count,...point});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:count,...point});}
    await new Promise(resolve=>setTimeout(resolve,150));
  };
  const menuItem=async(selector,label)=>{
    await evaluate('document.querySelector('+JSON.stringify(selector)+').dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true,clientX:400,clientY:400}))');
    await waitFor(win,'document.querySelector("[data-testid=mysql-result-menu]")','右键操作菜单');
    assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-preview-row-detail]"))'),false,'右键本身不能打开详情');
    await evaluate('[...document.querySelectorAll("[role=menuitem]")].find(e=>e.textContent.trim()==='+JSON.stringify(label)+').click()');
    await new Promise(resolve=>setTimeout(resolve,160));
  };
  const gutter=index=>visible+' tbody tr:nth-child('+index+') .mysql-edit-number button';
  const point=selector=>evaluate('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');if(!e.closest("[role=menu]"))e.scrollIntoView({block:"nearest",inline:"nearest"});const r=e.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()');
  const drag=async(from,to,modifiers=[],cancel=false)=>{
    win.webContents.focus();
    const a=await point(gutter(from)),b=await point(gutter(to));
    if(modifiers.includes('shift'))win.webContents.sendInputEvent({type:'keyDown',keyCode:'Shift'});
    win.webContents.sendInputEvent({type:'mouseMove',...a,modifiers});
    win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...a,modifiers});
    await new Promise(resolve=>setTimeout(resolve,40));
    win.webContents.sendInputEvent({type:'mouseMove',...b,modifiers});
    await new Promise(resolve=>setTimeout(resolve,50));
    if(cancel)await key('Escape');
    win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...b,modifiers});
    if(modifiers.includes('shift'))win.webContents.sendInputEvent({type:'keyUp',keyCode:'Shift'});
    await new Promise(resolve=>setTimeout(resolve,120));
  };
  const geometry=()=>evaluate('(()=>{const root=document.querySelector("[data-testid=mysql-data-editor]"),scroll=root.querySelector("[data-testid$=table-scroll]");return {cells:[...root.querySelectorAll("tbody tr:first-child td")].map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height]}),top:scroll.scrollTop,left:scroll.scrollLeft}})()');
  const stage=async(index,name,value,finish=true)=>{await doubleClick(cell(index,name));try{await waitFor(win,'document.querySelector('+JSON.stringify(cell(index,name)+' input')+')','双击显示原位输入框');}catch(error){process.stderr.write(await evaluate('document.querySelector("[data-testid=mysql-data-editor]")?.innerText')+'\n');await screenshot(win,'edit-failed');throw error;}await fill(win,cell(index,name)+' input',value);if(finish)await key('Enter');};
  const save=async()=>{await click(win,testId('mysql-edit-save'));await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.textContent.trim()==="保存更改" && document.querySelector("[data-testid=mysql-edit-save]")?.disabled','单次点击保存结束');assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-edit-confirm-dialog]"))'),false);};
  const sameGeometry=(actual,expected,message)=>{assert.equal(actual.top,expected.top,message);assert.equal(actual.left,expected.left,message);assert.equal(actual.cells.length,expected.cells.length,message);actual.cells.forEach((cell,index)=>cell.forEach((value,axis)=>assert.ok(Math.abs(value-expected.cells[index][axis])<=1,message)));};
  const button=async(text)=>{const index=await evaluate('Array.from(document.querySelectorAll("button")).findIndex(e=>e.getClientRects().length && (e.textContent.trim()==='+JSON.stringify(text)+' || e.getAttribute("aria-label")==='+JSON.stringify(text)+'))');assert.ok(index>=0,text);await evaluate('document.querySelectorAll("button")['+index+'].click()');await new Promise(resolve=>setTimeout(resolve,90));};
  await selectPlugin(win,PRIMARY_ID);
  await click(win,'[data-testid=mysql-table-item][data-table-name=orders]');
  await enter();
  assert.equal(await current(cell(1,'id')),'9007199254740993');
  await doubleClick(cell(1,'id'));
  assert.equal(await evaluate('Boolean(document.querySelector('+JSON.stringify(cell(1,'id')+' input')+'))'),false);
  await menuItem(cell(1,'label'),'编辑单元格');
  await waitFor(win,'document.querySelector('+JSON.stringify(cell(1,'label')+' input')+')','右键开始原位编辑');
  await fill(win,cell(1,'label')+' input','取消这个修改');await key('Escape');
  assert.equal(await current(cell(1,'label')),'测试记录 01');
  const initialRows=await fixture.read();
  await click(win,testId('mysql-add-row'));
  await waitFor(win,'document.querySelector("tr[data-row-state=insert] input")','新增直接进入表格编辑');
  assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-row-sheet]"))'),false,'添加行不再强制打开侧栏');
  await fill(win,'tr[data-row-state=insert] input','9999999999999999');await key('Enter');
  await doubleClick('tr[data-row-state=insert] [data-edit-column=label]');
  try { await waitFor(win,'document.querySelector("tr[data-row-state=insert] input")','草稿字段进入编辑'); } catch(error) { process.stderr.write(await evaluate('document.querySelector("[data-testid=mysql-data-editor]")?.innerText')+'\n'); throw error; }
  await fill(win,'tr[data-row-state=insert] input','新增行界面验证');await key('Enter');
  assert.match(await current('tr[data-row-state=insert] [data-edit-column=state]'),/默认：open/u);
  const draftGeometry=await evaluate('(()=>{const row=document.querySelector("tr[data-row-state=insert]"),normal=document.querySelector("tr[data-row-index]");return {height:row.getBoundingClientRect().height,normalHeight:normal.getBoundingClientRect().height,widths:[...row.cells].map(c=>c.getBoundingClientRect().width),normalWidths:[...normal.cells].map(c=>c.getBoundingClientRect().width)}})()');
  assert.equal(draftGeometry.height,draftGeometry.normalHeight,'新增草稿行高与普通行一致');assert.deepEqual(draftGeometry.widths,draftGeometry.normalWidths,'草稿按相同字段列对齐');
  await screenshot(win,'insert-grid');
  await click(win,'tr[data-row-state=insert] [aria-label="编辑完整行字段"]');
  await waitFor(win,'document.querySelector("[data-testid=mysql-row-sheet]")','可选完整字段侧栏');
  await screenshot(win,'insert-sheet');
  for(const zoom of [1.25,1.5]){
    win.webContents.setZoomFactor(zoom);await new Promise(resolve=>setTimeout(resolve,150));
    assert.equal(await evaluate('(()=>{const r=document.querySelector("[data-testid=mysql-stage-insert]").getBoundingClientRect();return r.right<=innerWidth&&r.bottom<=innerHeight&&r.left>=0})()'),true,'缩放后应用草稿按钮可见');
    await screenshot(win,'insert-sheet-zoom-'+zoom);
  }
  win.webContents.setZoomFactor(1);
  await click(win,testId('mysql-stage-insert'));
  await waitFor(win,'!document.querySelector("[data-testid=mysql-row-sheet]")','完整字段应用到草稿');
  assert.equal((await fixture.read()).length,initialRows.length,'暂存新增不能写库');
  await save();
  assert.equal((await fixture.read()).length,initialRows.length+1);
  await waitFor(win,'document.querySelector("[data-testid=mysql-data-editor] tbody tr[data-row-index]")','新增后刷新');
  await click(win,visible+' tbody tr[data-row-index="0"] .mysql-edit-row-selector button');
  await click(win,testId('mysql-copy-row'));
  await waitFor(win,'document.querySelector("tr[data-row-state=copy]")','复制直接出现在源行旁');
  await key('Escape');
  assert.equal(await current('tr[data-row-state=copy] [data-edit-column=label]'),initialRows[0].label);
  assert.equal(await evaluate('document.querySelector("tr[data-row-state=copy]").previousElementSibling.dataset.rowIndex'),'0','复制行紧邻源行');
  await doubleClick('tr[data-row-state=copy] [data-edit-column=id]');
  await fill(win,'tr[data-row-state=copy] input','9999999999999998');await key('Enter');
  await fill(win,testId('mysql-preview-filter'),'无法匹配任何原始行');
  assert.equal(await evaluate('document.querySelectorAll("tr[data-draft-row]").length'),1,'筛选不隐藏草稿');
  await fill(win,testId('mysql-preview-filter'),'');
  await click(win,testId('mysql-add-row'));await key('Escape');
  await stage(3,'label','统一取消验证');
  await click(win,visible+' tbody tr[data-row-index="0"] .mysql-edit-row-selector button');
  await click(win,testId('mysql-delete-rows'));
  await waitFor(win,'document.querySelector("tr[data-row-state=delete]")','混合草稿删除标记');
  const colors=await evaluate('Object.fromEntries(["insert","copy","delete"].map(state=>[state,getComputedStyle(document.querySelector("tr[data-row-state="+state+"] [data-edit-column]")).backgroundColor]))');
  assert.equal(new Set(Object.values(colors)).size,3,'新增、复制和删除具有不同底色');
  await screenshot(win,'mixed-drafts');
  for(const zoom of [1.25,1.5]){
    win.webContents.setZoomFactor(zoom);await new Promise(resolve=>setTimeout(resolve,120));
    assert.equal(await evaluate('(()=>{const buttons=[...document.querySelectorAll("[data-testid=mysql-edit-save],[data-testid=mysql-edit-undo]")];return buttons.every(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight})})()'),true,'缩放后保存和取消必须可见');
    assert.equal(await evaluate('(()=>{const e=document.querySelector("[data-testid=mysql-edit-dirty-count]");return e.getBoundingClientRect().right<=e.closest(".mysql-results-status").getBoundingClientRect().right+1})()'),true,'缩放后分类数量不截断');
    await screenshot(win,'compact-drafts-zoom-'+zoom);
  }
  win.webContents.setZoomFactor(1);

  await click(win,testId('mysql-edit-undo'));
  assert.equal(await evaluate('document.querySelectorAll("tr[data-row-state]").length'),0,'统一取消清除全部行状态');
  assert.equal(await current(cell(2,'label')),initialRows[1].label,'统一取消恢复修改原值');
  assert.equal((await fixture.read()).length,initialRows.length+1,'统一取消没有写库');
  await click(win,visible+' tbody tr[data-row-index="0"] .mysql-edit-row-selector button');
  await click(win,testId('mysql-delete-rows'));
  await waitFor(win,'document.querySelector("tr[data-pending-delete]")','标记待删除');
  assert.equal((await fixture.read()).length,initialRows.length+1,'标记删除不能写库');
  await screenshot(win,'delete-staged');
  await click(win,'[aria-label=撤销删除]');
  assert.equal(await evaluate('Boolean(document.querySelector("tr[data-pending-delete]"))'),false);
  await click(win,testId('mysql-delete-rows'));
  await click(win,testId('mysql-edit-save'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-confirm-delete]")','统一删除确认');
  await button('继续编辑');
  await click(win,testId('mysql-edit-undo'));
  const beforeEdit=await geometry();
  await doubleClick(cell(1,'label'));
  sameGeometry(await geometry(),beforeEdit,'进入单元格编辑不得改变列宽、行高、坐标和滚动位置');
  await fill(win,cell(1,'label')+' input',"界面修改 ' 参数化");
  await key('Enter');
  sameGeometry(await geometry(),beforeEdit,'暂存后表格位置不变');
  assert.equal((await fixture.read())[0].label,'测试记录 01','暂存不能立即写库');
  assert.match(await current(testId('mysql-edit-dirty-count')),/修改 1.*1 处/u);
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-row-selector button');
  await click(win,visible+' tbody tr:nth-child(2) .mysql-edit-row-selector button');
  await click(win,testId('mysql-edit-batch'));
  await fill(win,'[aria-label="批量赋值的新值"]','统一赋值');
  await click(win,testId('mysql-edit-apply-batch'));
  await waitFor(win,'!document.querySelector("[data-testid=mysql-edit-batch-dialog]")','批量赋值弹窗关闭');
  assert.match(await current(testId('mysql-edit-dirty-count')),/修改 2.*2 处/u);
  await screenshot(win,'edit-staged');
  await save();
  assert.deepEqual((await fixture.read()).slice(0,3).map(row=>row.label),['统一赋值','统一赋值','测试记录 03']);
  assert.match(await current(testId('mysql-edit-dirty-count')),/已保存/u);
  sameGeometry(await geometry(),beforeEdit,'保存后表格位置不变');
  await button('取消选择');
  await drag(1,4);
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr[data-selected]").length'),4,'行号拖选连续四行');
  assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-preview-row-detail]"))'),false,'拖选不能打开详情');
  await drag(4,2);
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr[data-selected]").length'),1,'从已选行反向拖动取消勾选');
  await drag(3,6,[],true);
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr[data-selected]").length'),1,'Esc 恢复拖动前选择');
  await drag(1,1);
  await drag(1,1);
  await drag(4,4,['shift']);
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr[data-selected]").length'),4,'Shift 连选四行');
  await menuItem(gutter(2),'批量修改已选 4 行…');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-batch-dialog]")','选中行右键批量修改');
  await button('取消');
  await waitFor(win,'!document.querySelector("[role=dialog]")','关闭批量窗口');
  await button('取消选择');
  await click(win,testId('mysql-preview-load-more'));
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===33','编辑后继续加载剩余行');
  await click(win,visible+' tbody tr:nth-child(33) .mysql-edit-row-selector button');
  await click(win,testId('mysql-delete-rows'));
  await waitFor(win,'document.querySelector("tr[data-pending-delete]")','新增测试行待删除');
  await click(win,testId('mysql-edit-save'));
  await click(win,testId('mysql-confirm-delete'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled && !document.querySelector("tr[data-pending-delete]")','删除事务完成');
  assert.equal((await fixture.read()).length,initialRows.length,'确认后只删除已选测试行');
  await click(win,testId('mysql-preview-load-more'));
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===32','删除刷新后继续加载');
  await stage(21,'label','追加页原位修改');
  await save();
  assert.equal((await fixture.read())[20].label,'追加页原位修改','追加行必须更新到正确主键');
  assert.equal((await fixture.read())[0].label,'统一赋值');
  await stage(1,'amount','9999999999999999.1234');
  await save();
  assert.equal((await fixture.read())[0].amount,'9999999999999999.1234','精确小数必须无损');
  await doubleClick(cell(1,'amount'));await key('Escape');
  await waitFor(win,'document.activeElement?.tagName === "TD"','退出输入后焦点返回单元格');
  await key('c',['control']);
  assert.equal(await evaluate('window.__databaseClipboardWrites.at(-1)'),'9999999999999999.1234');
  await menuItem(cell(1,'amount'),'查看行详情');
  await waitFor(win,'document.querySelector("[data-testid=mysql-preview-row-detail]")','行详情');
  assert.match(await current(testId('mysql-preview-row-detail')),/9999999999999999.1234/u);
  await click(win,testId('mysql-preview-close-detail'));
  await stage(3,'label','未保存的第三行');
  await drag(1,2);
  const writesBeforeExport=fixture.writes.length;
  await evaluate('document.querySelector('+JSON.stringify(gutter(1))+').dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true,clientX:400,clientY:400}))');
  await waitFor(win,'document.querySelector("[data-slot=context-menu-sub-trigger]")','SQL 子菜单');
  await new Promise(resolve=>setTimeout(resolve,200));
  await win.webContents.capturePage();
  await new Promise(resolve=>setTimeout(resolve,100));
  const subPoint=await point('[data-slot=context-menu-sub-trigger]');
  win.webContents.focus();
  win.webContents.sendInputEvent({type:'mouseMove',...subPoint});
  await new Promise(resolve=>setTimeout(resolve,200));
  await waitFor(win,'[...document.querySelectorAll("[role=menuitem]")].some(e=>e.textContent==="SELECT")','四类 SQL 菜单');
  await evaluate('[...document.querySelectorAll("[role=menuitem]")].find(e=>e.textContent==="SELECT").click()');
  await waitFor(win,'document.querySelector("[data-testid=mysql-sql-export-dialog]")','SQL 预览');
  await key('s',['control']);
  assert.equal(fixture.writes.length,writesBeforeExport,'SQL 预览内 Ctrl+S 不得保存底层表格的其他草稿');
  const generated=await evaluate('document.querySelector("[data-testid=mysql-sql-export-text]").value');
  assert.match(generated,/9007199254740993/u);assert.match(generated,/9007199254740994/u);assert.doesNotMatch(generated,/9007199254740995/u);
  await screenshot(win,'sql-export');
  await button('复制 SQL');
  assert.equal(await evaluate('window.__databaseClipboardWrites.at(-1)'),generated);
  for(const kind of ['INSERT','UPDATE','DELETE']){
    await click(win,'[aria-label="SQL 生成类型"]');
    await evaluate('[...document.querySelectorAll("[role=option]")].find(e=>e.textContent.trim()==='+JSON.stringify(kind)+').click()');
    await waitFor(win,'document.querySelector("[data-testid=mysql-sql-export-text]").value.includes('+JSON.stringify(kind==='INSERT'?'INSERT INTO':kind==='UPDATE'?'UPDATE ':'DELETE FROM')+')','切换 SQL 类型');
    const sql=await evaluate('document.querySelector("[data-testid=mysql-sql-export-text]").value');
    assert.match(sql,/9007199254740993/u);assert.match(sql,/9007199254740994/u);assert.doesNotMatch(sql,/9007199254740995/u);
    if(kind==='INSERT'){assert.match(sql,/9999999999999999.1234/u);assert.doesNotMatch(sql,/doubled/u);}
  }
  await button('保存 .sql');
  await waitFor(win,'[...document.querySelectorAll("button")].some(e=>e.textContent==="保存 .sql"&&!e.disabled)','导出文件完成');
  assert.match(await fixture.readExport(),/DELETE FROM/u);
  assert.equal(fixture.writes.length,writesBeforeExport,'生成、复制、保存四类 SQL 不得写入数据库');
  await button('关闭');await waitFor(win,'!document.querySelector("[role=dialog]")','关闭 SQL 预览');
  await button('取消选择');

  await stage(3,'label','未保存的第三行');
  await click(win,'[data-testid=mysql-table-close][data-table-name=orders]');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-discard-dialog]")','关闭标签保护');
  await button('保留修改');
  await waitFor(win,'!document.querySelector("[data-testid=mysql-edit-discard-dialog]")','保留草稿后关闭提示');
  assert.match(await current(cell(3,'label')),/未保存/u);
  await click(win,testId('mysql-sql-tab'));
  await fill(win,testId('mysql-sql-editor'),'SELECT id,label,amount,optional FROM orders ORDER BY id LIMIT 5');
  await click(win,testId('mysql-query-run'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-query-result]")','SQL 查询结果');
  await fill(win,testId('mysql-sql-editor'),'SELECT id,label FROM orders WHERE id=999');
  await enter();
  assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-edit-discard-dialog]"))'),false,'进入 SQL 结果时不应出现表草稿提示');
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length'),5,'编辑使用已执行 SQL');
  await fixture.external((await fixture.read())[4].id,'初次编辑前已变化');
  await stage(1,'label','SQL入口保存',false);
  await save();
  assert.equal((await fixture.read())[0].label,'SQL入口保存');
  await fill(win,testId('mysql-query-filter'),'测试记录 03');
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===1','筛选到第三条原始记录');
  const filteredGeometry=await geometry();
  await stage(1,'label','筛选后修改第三条');
  sameGeometry(await geometry(),filteredGeometry,'筛选后的编辑保持原位置');
  await save();
  assert.equal((await fixture.read())[2].label,'筛选后修改第三条','必须修改筛选命中的主键，不是第一条数据库记录');
  assert.equal((await fixture.read())[0].label,'SQL入口保存');
  await fill(win,testId('mysql-query-filter'),'筛选后修改第三条');
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===1 && document.querySelector("[data-testid=mysql-data-editor] tbody tr").textContent.includes("筛选后修改第三条")','重新筛选使用保存后的新值');
  assert.equal(await evaluate('document.querySelector("[data-testid=mysql-query-filter]").type'),'text','搜索框不显示浏览器原生第二个清除按钮');
  assert.equal(await evaluate('document.querySelector("[data-testid=mysql-query-filter]").parentElement.querySelectorAll("button").length'),1);
  await click(win,'[aria-label="清除结果筛选"]');
  assert.equal(await evaluate('document.activeElement?.dataset.testid'),'mysql-query-filter','清除后保留输入焦点');

  await doubleClick(cell(5,'label'));
  assert.equal(await evaluate('Boolean(document.querySelector('+JSON.stringify(cell(5,'label')+' input')+'))'),false,'首次快照前字段已变化时拒绝覆盖旧显示值');
  assert.match(await current(testId('mysql-edit-dirty-count')),/已变化/u);
  assert.equal((await fixture.read())[4].label,'初次编辑前已变化');
  await doubleClick(cell(1,'optional'));
  await evaluate('(()=>{const data=new DataTransfer();data.setData("text/plain","多行\\n内容");document.querySelector('+JSON.stringify(cell(1,'optional')+' input')+').dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:data}))})()');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-cell-dialog]")','完整字段编辑');
  await fill(win,'[data-testid=mysql-edit-cell-dialog] textarea','多行\n内容');
  await button('暂存修改');await save();
  assert.equal((await fixture.read())[0].optional,'多行\n内容');
  await menuItem(cell(1,'optional'),'完整字段编辑…');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-cell-dialog][data-state=open] textarea")?.value === "多行\\n内容"','菜单打开新的完整字段编辑');
  await button('设为 NULL');await save();
  assert.equal((await fixture.read())[0].optional,null);
  await stage(2,'label','不应覆盖并发修改');
  const second=(await fixture.read())[1];await fixture.external(second.id,'其他用户已修改');
  await save();
  await waitFor(win,'document.querySelector("[data-conflict]")','冲突行定位');
  assert.equal((await fixture.read())[1].label,'其他用户已修改');
  assert.equal(await evaluate('document.querySelector("[data-testid=mysql-edit-save]").disabled'),true);
  await screenshot(win,'edit-conflict');
  await click(win,testId('mysql-edit-refresh'));
  await click(win,testId('mysql-edit-discard-confirm'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled===true && !document.querySelector("[data-conflict]")','刷新冲突结果');
  await stage(2,'label','断连保留的草稿');
  plugins.find(p=>p.pluginInstanceId===PRIMARY_ID).assessment={phase:'disconnected',primaryStatus:{kind:'disconnected',label:'未连接',action:'connect'}};
  state.sequence++;win.webContents.send('v2:environment-status-changed',runtime());
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled===true','断连禁用保存');
  assert.match(await current(cell(2,'label')),/断连保留的草稿/u);
  assert.equal((await fixture.read())[1].label,'其他用户已修改');
  await screenshot(win,'edit-disconnected');
  assert.ok(fixture.audits.some(entry=>entry.auditAction==='mysql.update'&&entry.result==='success'&&entry.affectedRows===2));
  assert.doesNotMatch(JSON.stringify(fixture.audits),/SQL入口保存|统一赋值|多行/u);
  process.stdout.write('数据库编辑 UI 通过：两个入口、右键菜单、防误触、拖选与取消、四类 SQL 预览/复制/导出、主键只读、暂存、批量、单次保存、原位布局、精确小数、复制、行详情、NULL、多行、关闭保护、并发冲突及断连草稿（'+(fixture.live?'真实 MySQL':'隔离内存夹具')+'）。\n');
};
