const assert=require('node:assert/strict');

module.exports=async function({win,fixture,click,fill,waitFor,testId,screenshot,selectPlugin,PRIMARY_ID,plugins,state,runtime}){
  const evaluate=source=>win.webContents.executeJavaScript(source,true);
  const visible='[data-testid=mysql-data-editor]';
  const cell=(index,name)=>visible+' tbody tr:nth-child('+index+') [data-edit-column="'+name+'"]';
  const current=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+')?.textContent');
  const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await new Promise(resolve=>setTimeout(resolve,90));};
  const enter=async()=>{await click(win,testId('mysql-edit-open'));await waitFor(win,'document.querySelector("[data-testid=mysql-data-editor] tbody tr")','进入编辑模式');};
  const stage=async(index,name,value)=>{await click(win,cell(index,name)+' button');await fill(win,cell(index,name)+' input',value);await key('Enter');};
  const confirm=async()=>{await click(win,testId('mysql-edit-save'));await waitFor(win,'document.querySelector("[data-testid=mysql-edit-confirm-dialog]")','保存审阅');};
  const save=async()=>{await click(win,testId('mysql-edit-confirm-save'));await waitFor(win,'!document.querySelector("[data-testid=mysql-edit-confirm-dialog]")','提交完成');};
  const button=async(text)=>{const index=await evaluate('Array.from(document.querySelectorAll("button")).findIndex(e=>e.getClientRects().length && e.textContent.trim()==='+JSON.stringify(text)+')');assert.ok(index>=0,text);await evaluate('document.querySelectorAll("button")['+index+'].click()');await new Promise(resolve=>setTimeout(resolve,90));};
  await selectPlugin(win,PRIMARY_ID);
  await click(win,'[data-testid=mysql-table-item][data-table-name=orders]');
  await enter();
  assert.equal(await current(cell(1,'id')),'9007199254740993');
  await click(win,cell(1,'id')+' button');
  assert.equal(await evaluate('Boolean(document.querySelector('+JSON.stringify(cell(1,'id')+' input')+'))'),false);
  await click(win,cell(1,'label')+' button');
  await fill(win,cell(1,'label')+' input','取消这个修改');await key('Escape');
  assert.equal(await current(cell(1,'label')),'测试记录 01');
  await stage(1,'label',"界面修改 ' 参数化");
  assert.equal((await fixture.read())[0].label,'测试记录 01','暂存不能立即写库');
  assert.match(await current(testId('mysql-edit-dirty-count')),/1 行.*1 处/u);
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-row-selector button');
  await click(win,visible+' tbody tr:nth-child(2) .mysql-edit-row-selector button');
  await click(win,testId('mysql-edit-batch'));
  await fill(win,'[aria-label="批量赋值的新值"]','统一赋值');
  await click(win,testId('mysql-edit-apply-batch'));
  await waitFor(win,'!document.querySelector("[data-testid=mysql-edit-batch-dialog]")','批量赋值弹窗关闭');
  assert.match(await current(testId('mysql-edit-dirty-count')),/2 行.*2 处/u);
  await screenshot(win,'edit-staged');
  await confirm();
  assert.match(await current(testId('mysql-edit-confirm-dialog')),/9007199254740993/u);
  assert.match(await current(testId('mysql-edit-confirm-dialog')),/测试记录 01/u);
  assert.match(await current(testId('mysql-edit-confirm-dialog')),/统一赋值/u);
  assert.equal((await fixture.read())[0].label,'测试记录 01');
  await screenshot(win,'edit-review');
  await save();
  assert.deepEqual((await fixture.read()).slice(0,3).map(row=>row.label),['统一赋值','统一赋值','测试记录 03']);
  assert.match(await current(testId('mysql-edit-dirty-count')),/尚无/u);
  await button('取消选择');
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-row-selector button');
  await evaluate('document.querySelector('+JSON.stringify(visible+' tbody tr:nth-child(4) .mysql-edit-row-selector')+').dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,shiftKey:true}))');
  await click(win,visible+' tbody tr:nth-child(4) .mysql-edit-row-selector button');
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr[data-selected]").length'),4,'Shift 连选四行');
  await button('取消选择');
  await stage(1,'amount','9999999999999999.1234');
  await confirm();await save();
  assert.equal((await fixture.read())[0].amount,'9999999999999999.1234','精确小数必须无损');
  await click(win,cell(1,'amount')+' button');await key('Escape');await key('c',['control']);
  assert.equal(await evaluate('window.__databaseClipboardWrites.at(-1)'),'9999999999999999.1234');
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-number button');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-row-detail]")','行详情');
  assert.match(await current(testId('mysql-edit-row-detail')),/9999999999999999.1234/u);
  await click(win,testId('mysql-edit-close-detail'));
  await stage(3,'label','未保存的第三行');
  await click(win,'[data-testid=mysql-table-close][data-table-name=orders]');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-discard-dialog]")','关闭标签保护');
  await button('保留修改');
  assert.match(await current(cell(3,'label')),/未保存/u);
  await click(win,testId('mysql-sql-tab'));
  await fill(win,testId('mysql-sql-editor'),'SELECT id,label,amount,optional FROM orders ORDER BY id LIMIT 5');
  await click(win,testId('mysql-query-run'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-query-result]")','SQL 查询结果');
  await fill(win,testId('mysql-sql-editor'),'SELECT id,label FROM orders WHERE id=999');
  await enter();
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length'),5,'编辑使用已执行 SQL');
  await stage(1,'label','SQL入口保存');
  await confirm();await save();
  assert.equal((await fixture.read())[0].label,'SQL入口保存');
  await click(win,cell(1,'optional')+' button');
  await evaluate('(()=>{const data=new DataTransfer();data.setData("text/plain","多行\\n内容");document.querySelector('+JSON.stringify(cell(1,'optional')+' input')+').dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:data}))})()');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-cell-dialog]")','完整字段编辑');
  await fill(win,'[data-testid=mysql-edit-cell-dialog] textarea','多行\n内容');
  await button('暂存修改');await confirm();await save();
  assert.equal((await fixture.read())[0].optional,'多行\n内容');
  await evaluate('document.querySelector('+JSON.stringify(cell(1,'optional')+' button')+').dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true}))');
  await button('设为 NULL');await confirm();await save();
  assert.equal((await fixture.read())[0].optional,null);
  await stage(2,'label','不应覆盖并发修改');
  const second=(await fixture.read())[1];await fixture.external(second.id,'其他用户已修改');
  await confirm();await save();
  await waitFor(win,'document.querySelector("[data-conflict]")','冲突行定位');
  assert.equal((await fixture.read())[1].label,'其他用户已修改');
  assert.equal(await evaluate('document.querySelector("[data-testid=mysql-edit-save]").disabled'),true);
  await screenshot(win,'edit-conflict');
  await click(win,testId('mysql-edit-refresh'));
  await click(win,testId('mysql-edit-discard-confirm'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled===true && !document.querySelector("[data-conflict]")','刷新冲突结果');
  await stage(2,'label','断连保留的草稿');
  plugins.find(p=>p.pluginInstanceId===PRIMARY_ID).assessment={phase:'disconnected',primaryStatus:{kind:'disconnected',label:'未连接',action:'connect'}};
  state.sequence++;win.webContents.send('v2:environment-status-changed',runtime());
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled===true','断连禁用保存');
  assert.match(await current(cell(2,'label')),/断连保留的草稿/u);
  assert.equal((await fixture.read())[1].label,'其他用户已修改');
  await screenshot(win,'edit-disconnected');
  assert.ok(fixture.audits.some(entry=>entry.auditAction==='mysql.update'&&entry.result==='success'&&entry.affectedRows===2));
  assert.doesNotMatch(JSON.stringify(fixture.audits),/SQL入口保存|统一赋值|多行/u);
  process.stdout.write('数据库编辑 UI 通过：两个入口、主键只读、暂存、批量、确认、精确小数、复制、行详情、NULL、多行、关闭保护、并发冲突及断连草稿（'+(fixture.live?'真实 MySQL':'隔离内存夹具')+'）。\n');
};
