const assert = require('node:assert/strict');
module.exports = async function ({win,fill,click,waitFor,textContains,testId,screenshot,state,databaseCalls,PRIMARY_ID,clipboard,openRowDetail}) {
  const evaluate = source => win.webContents.executeJavaScript(source,true);
  state.browseFixture = true;
  await click(win,'[data-testid=mysql-table-document-tab][data-table-name=orders]');
  await fill(win,testId('mysql-table-where'),'id >= 51');
  await click(win,testId('mysql-preview-run'));
  await textContains(win,'mysql-preview-summary','返回 15 行');
  const before = databaseCalls.length;
  await click(win,'[data-testid=mysql-table-item][data-table-name=orders]');
  assert.equal(databaseCalls.length,before,'重复点击表不得重复查询');
  await click(win,testId('mysql-tables-load-more'));
  await click(win,'[data-testid=mysql-table-item][data-table-name=archived_orders]');
  await textContains(win,'mysql-preview-summary','返回 20 行');
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-table-document-tab]').length"),2);
  await fill(win,testId('mysql-table-where'),'id >= 61');
  await click(win,testId('mysql-preview-load-more'));
  await textContains(win,'mysql-preview-summary','返回 40 行');
  await evaluate("document.querySelector('[data-testid=mysql-preview-table-scroll]').scrollTop=180");
  const beforeSwitch = databaseCalls.length;
  await click(win,'[data-testid=mysql-table-document-tab][data-table-name=orders]');
  await textContains(win,'mysql-preview-summary','返回 15 行');
  assert.equal(await evaluate("document.querySelector('[data-testid=mysql-table-where]').value"),'id >= 51');
  assert.equal(databaseCalls.length,beforeSwitch,'切表恢复数据无需重新读取');
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-preview-result]').length"),1,'后台表不保留表格 DOM');
  await fill(win,testId('mysql-table-where'),'');
  await evaluate("(() => { const transfer=new DataTransfer(); const header=document.querySelector('[data-testid=mysql-preview-sort][data-column=label]'); header.dispatchEvent(new DragEvent('dragstart',{dataTransfer:transfer,bubbles:true})); const input=document.querySelector('[data-testid=mysql-table-where]'); input.focus(); input.setSelectionRange(0,0); input.dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true})); })()");
  await waitFor(win,"document.querySelector('[data-testid=mysql-table-where]').value === '`label` '",'拖字段填入筛选条件');
  assert.equal(databaseCalls.length,beforeSwitch,'拖字段不自动执行筛选');
  await evaluate("(() => { const transfer=new DataTransfer(); transfer.setData('application/x-runbook-mysql-column',JSON.stringify({workspace:'other',table:'orders',column:'id'})); document.querySelector('[data-testid=mysql-table-where]').dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true})); })()");
  assert.equal(await evaluate("document.querySelector('[data-testid=mysql-table-where]').value"),'`label` ');
  assert.equal(await evaluate("document.querySelector('[data-testid=mysql-workspace-density]')"),null,'数据库工作区固定紧凑布局，不提供密度切换');
  await openRowDetail(win,'[data-testid=mysql-preview-row][data-row-index="0"]');
  await evaluate("window.__previousClipboard = navigator.clipboard; Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new DOMException('Permission denied','NotAllowedError')}}})");
  await click(win,testId('mysql-preview-copy-row'));
  await waitFor(win,"document.body.textContent.includes('整行 JSON 已复制')",'权限受限时仍能复制整行');
  assert.deepEqual(JSON.parse(clipboard.readText()),{id:65,label:'浏览记录 65',optional:null});
  await click(win,'[data-testid=mysql-preview-copy-cell][data-column-name=label]');
  assert.equal(clipboard.readText(),'浏览记录 65');
  await evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:window.__previousClipboard}); delete window.__previousClipboard");
  await click(win,testId('mysql-preview-close-detail'));
  await screenshot(win,'multiple-tables');
  const late = {channel:'v2:mysql-preview-table',pluginInstanceId:PRIMARY_ID,result:require('./database-assist-ui.cjs').browseFixture({offset:20})};
  await click(win,'[data-testid=mysql-table-document-tab][data-table-name=archived_orders]');
  assert.equal(await evaluate("document.querySelector('[data-testid=mysql-table-where]').value"),'id >= 61');
  assert.ok(await evaluate("document.querySelector('[data-testid=mysql-preview-table-scroll]').scrollTop >= 179"),'恢复表格滚动位置');
  state.holdNext = late;
  await click(win,testId('mysql-preview-load-more'));
  await waitFor(win,"document.querySelector('[data-testid=mysql-preview-load-more]').textContent.includes('加载中')",'关闭前保持一个在途请求');
  await click(win,'[data-testid=mysql-table-close][data-table-name=archived_orders]');
  late.release();
  await textContains(win,'mysql-preview-summary','返回 15 行');
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-table-document-tab]').length"),1);
  state.extraTables = true;
  await click(win,testId('mysql-tables-refresh'));
  await textContains(win,'mysql-table-list','fixture_6');
  for (let index=1;index<=5;index++) {
    await click(win,'[data-testid=mysql-table-item][data-table-name=fixture_'+index+']');
    await textContains(win,'mysql-preview-summary','返回 20 行');
  }
  const atLimit = databaseCalls.length;
  await click(win,'[data-testid=mysql-table-item][data-table-name=fixture_6]');
  assert.equal(databaseCalls.length,atLimit,'达到表标签上限不能继续发起请求');
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-table-document-tab]').length"),6);
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-preview-result]').length"),1);
  await require('./workspace-layout-ui.cjs')({evaluate,until:(expression,label)=>waitFor(win,expression,label),win,root:'[data-testid=mysql-database-workspace]'});
  state.extraTables = false;
  await click(win,testId('mysql-workspace-close'));
  await click(win,testId('mysql-workspace-confirm-close'));
  await click(win,testId('plugin-workspace-open'));
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-table-document-tab]').length"),0,'关闭工作区清除全部表标签');
  state.allowDisconnect = true;
  state.failDisconnect = true;
  await click(win,testId('mysql-workspace-disconnect'));
  await waitFor(win,"document.body.textContent.includes('模拟断开失败')",'断开失败保留工作区');
  assert.equal(await evaluate("document.querySelectorAll('[data-testid=mysql-database-workspace]').length"),1);
  state.failDisconnect = false;
  await click(win,testId('mysql-workspace-disconnect'));
  await waitFor(win,"document.querySelector('[data-testid=mysql-full-window-workspace]') === null",'成功断开清理数据库工作区');
  state.allowDisconnect = false;
  state.browseFixture = false;
};
