const assert=require('node:assert/strict');

module.exports=async function({win,fixture,click,fill,waitFor,testId,screenshot,selectPlugin,PRIMARY_ID,plugins,state,runtime}){
  const evaluate=source=>win.webContents.executeJavaScript(source,true);
  const visible='[data-testid=mysql-data-editor]';
  const cell=(index,name)=>visible+' tbody tr:nth-child('+index+') [data-edit-column="'+name+'"]';
  const current=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+')?.textContent');
  const key=async(keyCode,modifiers=[])=>{win.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});win.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await new Promise(resolve=>setTimeout(resolve,90));};
  const enter=async()=>{await waitFor(win,'document.querySelector("[data-testid=mysql-data-editor] tbody tr")','显示结果表格');assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-edit-open]"))'),false);};
  const doubleClick=async selector=>{
    await waitFor(win,'!document.querySelector("[role=dialog]")','等待弹窗退出动画结束');
    const point=await evaluate('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');e.scrollIntoView({block:"nearest",inline:"nearest"});const r=e.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()');
    const hit=await evaluate('document.elementFromPoint('+point.x+','+point.y+')?.outerHTML');
    assert.ok(await evaluate('document.querySelector('+JSON.stringify(selector)+')?.contains(document.elementFromPoint('+point.x+','+point.y+'))'), '双击坐标必须落在目标单元格：'+hit);
    for(const count of [1,2]){win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:count,...point});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:count,...point});}
    await new Promise(resolve=>setTimeout(resolve,150));
  };
  const geometry=()=>evaluate('(()=>{const root=document.querySelector("[data-testid=mysql-data-editor]"),scroll=root.querySelector("[data-testid$=table-scroll]");return {cells:[...root.querySelectorAll("tbody tr:first-child td")].map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height]}),top:scroll.scrollTop,left:scroll.scrollLeft}})()');
  const stage=async(index,name,value,finish=true)=>{await doubleClick(cell(index,name));try{await waitFor(win,'document.querySelector('+JSON.stringify(cell(index,name)+' input')+')','双击显示原位输入框');}catch(error){process.stderr.write(await evaluate('document.querySelector("[data-testid=mysql-data-editor]")?.innerText')+'\n');await screenshot(win,'edit-failed');throw error;}await fill(win,cell(index,name)+' input',value);if(finish)await key('Enter');};
  const save=async()=>{await click(win,testId('mysql-edit-save'));await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.textContent.trim()==="保存" && document.querySelector("[data-testid=mysql-edit-save]")?.disabled','单次点击保存结束');assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-edit-confirm-dialog]"))'),false);};
  const sameGeometry=(actual,expected,message)=>{assert.equal(actual.top,expected.top,message);assert.equal(actual.left,expected.left,message);assert.equal(actual.cells.length,expected.cells.length,message);actual.cells.forEach((cell,index)=>cell.forEach((value,axis)=>assert.ok(Math.abs(value-expected.cells[index][axis])<=1,message)));};
  const button=async(text)=>{const index=await evaluate('Array.from(document.querySelectorAll("button")).findIndex(e=>e.getClientRects().length && e.textContent.trim()==='+JSON.stringify(text)+')');assert.ok(index>=0,text);await evaluate('document.querySelectorAll("button")['+index+'].click()');await new Promise(resolve=>setTimeout(resolve,90));};
  await selectPlugin(win,PRIMARY_ID);
  await click(win,'[data-testid=mysql-table-item][data-table-name=orders]');
  await enter();
  assert.equal(await current(cell(1,'id')),'9007199254740993');
  await doubleClick(cell(1,'id'));
  assert.equal(await evaluate('Boolean(document.querySelector('+JSON.stringify(cell(1,'id')+' input')+'))'),false);
  await doubleClick(cell(1,'label'));
  await fill(win,cell(1,'label')+' input','取消这个修改');await key('Escape');
  assert.equal(await current(cell(1,'label')),'测试记录 01');
  const beforeEdit=await geometry();
  await doubleClick(cell(1,'label'));
  sameGeometry(await geometry(),beforeEdit,'进入单元格编辑不得改变列宽、行高、坐标和滚动位置');
  await fill(win,cell(1,'label')+' input',"界面修改 ' 参数化");
  await key('Enter');
  sameGeometry(await geometry(),beforeEdit,'暂存后表格位置不变');
  assert.equal((await fixture.read())[0].label,'测试记录 01','暂存不能立即写库');
  assert.match(await current(testId('mysql-edit-dirty-count')),/1 行.*1 处/u);
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-row-selector button');
  await click(win,visible+' tbody tr:nth-child(2) .mysql-edit-row-selector button');
  await click(win,testId('mysql-edit-batch'));
  await fill(win,'[aria-label="批量赋值的新值"]','统一赋值');
  await click(win,testId('mysql-edit-apply-batch'));
  await waitFor(win,'!document.querySelector("[data-testid=mysql-edit-batch-dialog]")','批量赋值弹窗关闭');
  assert.match(await current(testId('mysql-edit-dirty-count')),/2 行.*2 处/u);
  await screenshot(win,'edit-staged');
  await save();
  assert.deepEqual((await fixture.read()).slice(0,3).map(row=>row.label),['统一赋值','统一赋值','测试记录 03']);
  assert.match(await current(testId('mysql-edit-dirty-count')),/已保存/u);
  sameGeometry(await geometry(),beforeEdit,'保存后表格位置不变');
  await button('取消选择');
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-row-selector button');
  await evaluate('document.querySelector('+JSON.stringify(visible+' tbody tr:nth-child(4) .mysql-edit-row-selector')+').dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,shiftKey:true}))');
  await click(win,visible+' tbody tr:nth-child(4) .mysql-edit-row-selector button');
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr[data-selected]").length'),4,'Shift 连选四行');
  await button('取消选择');
  await click(win,testId('mysql-preview-load-more'));
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===32','编辑后继续加载剩余行');
  await stage(21,'label','追加页原位修改');
  await save();
  assert.equal((await fixture.read())[20].label,'追加页原位修改','追加行必须更新到正确主键');
  assert.equal((await fixture.read())[0].label,'统一赋值');
  await stage(1,'amount','9999999999999999.1234');
  await save();
  assert.equal((await fixture.read())[0].amount,'9999999999999999.1234','精确小数必须无损');
  await doubleClick(cell(1,'amount'));await key('Escape');
  await waitFor(win,'document.activeElement?.tagName === "TD"','退出输入后焦点返回单元格');
  await key('c',['control']);
  assert.equal(await evaluate('window.__databaseClipboardWrites.at(-1)'),'9999999999999999.1234');
  await click(win,visible+' tbody tr:nth-child(1) .mysql-edit-number button');
  await waitFor(win,'document.querySelector("[data-testid=mysql-preview-row-detail]")','行详情');
  assert.match(await current(testId('mysql-preview-row-detail')),/9999999999999999.1234/u);
  await click(win,testId('mysql-preview-close-detail'));
  await stage(3,'label','未保存的第三行');
  await click(win,'[data-testid=mysql-table-close][data-table-name=orders]');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-discard-dialog]")','关闭标签保护');
  await button('保留修改');
  await waitFor(win,'!document.querySelector("[data-testid=mysql-edit-discard-dialog]")','保留草稿后关闭提示');
  assert.match(await current(cell(3,'label')),/未保存/u);
  await click(win,testId('mysql-sql-tab'));
  await fill(win,testId('mysql-sql-editor'),'SELECT id,label,amount,optional FROM orders ORDER BY id LIMIT 5');
  await click(win,testId('mysql-query-run'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-query-result]")','SQL 查询结果');
  await fill(win,testId('mysql-sql-editor'),'SELECT id,label FROM orders WHERE id=999');
  await enter();
  assert.equal(await evaluate('Boolean(document.querySelector("[data-testid=mysql-edit-discard-dialog]"))'),false,'进入 SQL 结果时不应出现表草稿提示');
  assert.equal(await evaluate('document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length'),5,'编辑使用已执行 SQL');
  await fixture.external((await fixture.read())[4].id,'初次编辑前已变化');
  await stage(1,'label','SQL入口保存',false);
  await save();
  assert.equal((await fixture.read())[0].label,'SQL入口保存');
  await fill(win,testId('mysql-query-filter'),'测试记录 03');
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===1','筛选到第三条原始记录');
  const filteredGeometry=await geometry();
  await stage(1,'label','筛选后修改第三条');
  sameGeometry(await geometry(),filteredGeometry,'筛选后的编辑保持原位置');
  await save();
  assert.equal((await fixture.read())[2].label,'筛选后修改第三条','必须修改筛选命中的主键，不是第一条数据库记录');
  assert.equal((await fixture.read())[0].label,'SQL入口保存');
  await fill(win,testId('mysql-query-filter'),'筛选后修改第三条');
  await waitFor(win,'document.querySelectorAll("[data-testid=mysql-data-editor] tbody tr").length===1 && document.querySelector("[data-testid=mysql-data-editor] tbody tr").textContent.includes("筛选后修改第三条")','重新筛选使用保存后的新值');
  await fill(win,testId('mysql-query-filter'),'');

  await doubleClick(cell(5,'label'));
  assert.equal(await evaluate('Boolean(document.querySelector('+JSON.stringify(cell(5,'label')+' input')+'))'),false,'首次快照前字段已变化时拒绝覆盖旧显示值');
  assert.match(await current(testId('mysql-edit-dirty-count')),/已变化/u);
  assert.equal((await fixture.read())[4].label,'初次编辑前已变化');
  await doubleClick(cell(1,'optional'));
  await evaluate('(()=>{const data=new DataTransfer();data.setData("text/plain","多行\\n内容");document.querySelector('+JSON.stringify(cell(1,'optional')+' input')+').dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:data}))})()');
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-cell-dialog]")','完整字段编辑');
  await fill(win,'[data-testid=mysql-edit-cell-dialog] textarea','多行\n内容');
  await button('暂存修改');await save();
  assert.equal((await fixture.read())[0].optional,'多行\n内容');
  await evaluate('document.querySelector('+JSON.stringify(cell(1,'optional'))+').dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:true}))');
  await button('设为 NULL');await save();
  assert.equal((await fixture.read())[0].optional,null);
  await stage(2,'label','不应覆盖并发修改');
  const second=(await fixture.read())[1];await fixture.external(second.id,'其他用户已修改');
  await save();
  await waitFor(win,'document.querySelector("[data-conflict]")','冲突行定位');
  assert.equal((await fixture.read())[1].label,'其他用户已修改');
  assert.equal(await evaluate('document.querySelector("[data-testid=mysql-edit-save]").disabled'),true);
  await screenshot(win,'edit-conflict');
  await click(win,testId('mysql-edit-refresh'));
  await click(win,testId('mysql-edit-discard-confirm'));
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled===true && !document.querySelector("[data-conflict]")','刷新冲突结果');
  await stage(2,'label','断连保留的草稿');
  plugins.find(p=>p.pluginInstanceId===PRIMARY_ID).assessment={phase:'disconnected',primaryStatus:{kind:'disconnected',label:'未连接',action:'connect'}};
  state.sequence++;win.webContents.send('v2:environment-status-changed',runtime());
  await waitFor(win,'document.querySelector("[data-testid=mysql-edit-save]")?.disabled===true','断连禁用保存');
  assert.match(await current(cell(2,'label')),/断连保留的草稿/u);
  assert.equal((await fixture.read())[1].label,'其他用户已修改');
  await screenshot(win,'edit-disconnected');
  assert.ok(fixture.audits.some(entry=>entry.auditAction==='mysql.update'&&entry.result==='success'&&entry.affectedRows===2));
  assert.doesNotMatch(JSON.stringify(fixture.audits),/SQL入口保存|统一赋值|多行/u);
  process.stdout.write('数据库编辑 UI 通过：两个入口、主键只读、暂存、批量、单次保存、原位布局、精确小数、复制、行详情、NULL、多行、关闭保护、并发冲突及断连草稿（'+(fixture.live?'真实 MySQL':'隔离内存夹具')+'）。\n');
};
